name: BiliHelper

on:
  schedule:
  - cron: '0 1 * * *'
  push:
  workflow_dispatch:
    inputs:
      cache:
        description: 'cache'
        required: false
        default: 'true'
      ssh:
        description: 'ssh'
        required: false
        default: 'false'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        repository: 'lkeme/BiliHelper-personal'

    - name: Init config folder
      run: cp -r profile/example profile/user

    - name: Restore token
      if: github.event.inputs.cache != 'false'
      uses: actions/cache@v3
      with:
        path: |
          ./profile/user/
        key: ${{ github.workflow }}-v2-${{ github.run_id }}
        restore-keys: |
          ${{ github.workflow }}-v2-

    - name: Config
      env:
        config: ${{ secrets.config }}
      run: |
        echo "$config"|base64 -d > profile/user/config/user.ini

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v3
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress

    - name: Set proxy
      uses: w311ang/setproxy@main
      with:
        config: ${{ secrets.ss_config }}
        password: ${{ secrets.frp_auth }}
        redirect: ${{ secrets.frp_redirect }}

    - name: Run test suite
      run: timeout 30 php app.php m:a || echo Timeout!

    - name: SSH connection to Actions
      if: github.event.inputs.ssh == 'true'
      uses: P3TERX/ssh2actions@v1.0.0
      env:
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
